#nullable enable

// <auto-generated>
// This file is automatically generated by PropertyWrapperGenerator.
// Do not modify this file manually.
// </auto-generated>

    public partial class PlayerPart
    {
        public float MoveSpeed
        {
            get => Model.MoveSpeed.Value;
            set => Model.MoveSpeed.SetValue(value, this);
        }

        public float AttackPower
        {
            get => Model.AttackPower.Value;
            set => Model.AttackPower.SetValue(value, this);
        }

        public int Health
        {
            get => Model.Health.Value;
            set => Model.Health.SetValue(value, this);
        }

        public float TotalDamage
        {
            get => Model.TotalDamage.Value;
        }

    }
